### PR TITLE
fix of darwin + chrome-remote situation

### PR DESCRIPTION
**Pull request by filiprichtarik**
reverting unwanted change of behavior on osx + remote chrome reported by r-roos

### CODE REVIEW

**Comment by r-roos** [comment]
@filiprichtarik @luciano-renzi I have updated the branch with the suggested update I made earlier. Please review

**Comment by filiprichtarik** [comment]
this nut is for luciano to crack 

i understand your code, i understand even why chrome-remote does not trigger the condition ('chrome'==browser_definition['name']
is in this case 'chrome'=='chrome-remote' and returns false as expected)

but i have no idea how it works with remote browsers

and for the point of removing the workaround when 2.44 is out, we cannot 
we can only change the logic so it'll check chromedriver version too, otherwise everyone who doesn't have latest driver will have the issue back

**Comment by r-roos** [comment]
Hi @filiprichtarik your remark about not wanting to remove the work around triggered to look a bit closer to this issue. If you look at the current patch it is also silly all other version prior to driver 2.4.3 and chrome 70 are affected.

Regarding looking about more into detail. it seem we can retrieve a lot of information from the driver.capabilities, enough in fact to specifically target release version where we want to skip the maximize window feature.

Some debugging example of running chromedriver 2.4.3 & chrome 70. 
image

Now when using a remote driver 
image

I propose we rework the workaround to specifically target the affected versions of chromedriver & chrome

**Comment by luciano-renzi** [comment]
As @r-roos points out, the instance of the WebDriver has a dictionary of the capabilities used by it. This should be used here to stop maximizing the browser when it's running on mac locally or on a mac node regardless of the OS running Golem.

I tested the following condition and it looks good to me:
```python
is_mac = 'mac' in driver.capabilities.get('platform', '').lower()
if not ('chrome' in browser_definition['name'] and is_mac):
    driver.maximize_window()
```

We can add a version check once this is fixed. In the meantime, there are alternatives to maximizing Chrome. I'll add a comment in the ticket explaining.

**Comment by luciano-renzi** [comment]
Added my fix :-) It's tested in Chrome remote in and a macOS node. It's not tested in macOS local

@r-roos I'll leave this open in case you want to test that scenario

**Comment by r-roos** [comment]
@luciano-renzi your latest change seem to work well. 

Tested 
- Chrome local on a mac -> no window maximizing
- chrome-remote & chrome_zalenium of the settings posted earlier, which will maximize the window

**Pull request merged**
